### ISSUE TITLE
Fails when run with testcafe-live

### ISSUE THREAD

**Issue by borisdiakur** [helen-dikareva/axe-testcafe#4]
This is my test:
```js
import axeCheck from 'axe-testcafe'

fixture('My page')
  .page('http://localhost:3210/my-page.html')

test('a11y', async t => {
  await axeCheck(t)
})

```

Here is how I run the test:
```bash
testcafe-live safari myPage.fixture.js
```

This is the result:
```bash
Test run is starting...
 Running tests in:
 - Safari 11.1.0 / Mac OS X 10.13.4

 My page
 ✖ a11y

   1) Error: Cannot prepare tests due to an error.

      The "boundTestRun" option value is expected to be a test controller.

      Browser: Safari 11.1.0 / Mac OS X 10.13.4

         55 |        });
         56 |    })
         57 |});
         58 |
         59 |module.exports = function axeCheck (t, context, options) {
       > 60 |    return hasAxe.with({ boundTestRun: t })()
         61 |        .then(function (result) {
         62 |            if (!result)
         63 |                return injectAxe.with({ boundTestRun: t })();
         64 |
         65 |            return Promise.resolve();

         at axeCheck (.../node_modules/axe-testcafe/index.js:60:23)
         at <anonymous> (.../test/e2e/page/my-page/fixture/myPage.fixture.js:11:37)
         ...
```

If I run the test with `testcafe` instead of `testcafe-live` everything is fine.

**Comment by rob4629** [comment]
I think this is now resolved. It's working for me when I do `testcafe -L safari`

**Comment by benlind** [comment]
I'm also running into this when using Yarn Workspaces in a monorepo. I had to pull the axe-testcafe into our monorepo as its own package to get this to work.
